kind: Deployment
apiVersion: apps/v1
metadata:
  name: docviewzlb
  namespace: app
  labels:
    app: docviewzlb
    app.kubernetes.io/managed-by: Helm
    app.kubesphere.io/instance: docviewzlb
    chart: docviewzlb-1.0.0
    release: docviewzlb
    velero.io/backup-name: app
    velero.io/restore-name: app-20230606094257
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubesphere.io/creator: admin
    meta.helm.sh/release-name: docviewzlb
    meta.helm.sh/release-namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docviewzlb
      release: docviewzlb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: docviewzlb
        release: docviewzlb
      annotations:
        kubesphere.io/creator: admin
    spec:
      volumes:
        - name: time
          hostPath:
            path: /etc/localtime
            type: ''
      containers:
        - name: docviewzlb
          image: 'hzent.amberdata.cn:8082/docview_zlb:4.0'
          command:
            - nginx
            - '-g'
            - daemon off;
          ports:
            - name: hostport
              containerPort: 7014
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: time
              readOnly: true
              mountPath: /etc/localtime
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: dev
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
