server:
  port: 8888
  servlet:
    context-path: /dataarchivesapi
spring:
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
  application:
    name: dataarchives
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.base.svc.cluster.local:3306/dataarchives?useUnicode=true&characterEncoding=UTF-8&&useSSL=false
    username: root
    password: Dctm@1234
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  messages:
    basename: i18n/messages
    encoding: UTF-8
  redis:
    host: redis.base.svc.cluster.local
    port: 6379
    password: Dctm@1234
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: -1
        min-idle: 5
  quartz:
    # 将任务等保存化到数据库
    job-store-type: jdbc
    # 程序结束时会等待quartz相关的内容结束
    wait-for-jobs-to-complete-on-shutdown: true
    # QuartzScheduler启动时更新己存在的Job,这样就不用每次修改targetObject后删除qrtz_job_details表对应记录
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          # scheduler相关
          scheduler:
            # scheduler的实例名
            instanceName: scheduler
            instanceId: AUTO
          # 持久化相关
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            # 表示数据库中相关表是QRTZ_开头的
            tablePrefix: QRTZ_
            useProperties: false
            isClustered: true
            instanceId: AUTO
          # 线程池相关
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            # 线程数
            threadCount: 5
            # 线程优先级
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
logging:
  path: ./logs
  level:
    root: INFO

swagger:
  enabled:true

company:
  buss:
    user: dangan
    password: Dangan@123
    token-url: https://www.jhjtjggs.com/buss/japi/filemanageAPI/getToken
    folder-url: https://www.jhjtjggs.com/buss/japi/filemanageAPI/getLeftZree
    file-url: https://www.jhjtjggs.com/buss/japi/filemanageAPI/getFileZip
    business-url: https://www.jhjtjggs.com/buss/japi/filemanageAPI/getBusinessList
    flow-url: https://www.jhjtjggs.com/buss/japi/filemanageAPI/getFlowList
    attachment-url: https://www.jhjtjggs.com/buss/japi/filemanageAPI/getAnnexList
    bg_business_type: BGSQ,BGBG,DJBG,BGTZ
    system_code: amber-gh
    business_code: GCDA
    unit_code: 20001
    unit_name: 广互互联网法院

cn:
  amberdata:
    cdn:
      host: https://da.nbjb.gov.cn/cdn/
    index:
      hash: b6e42aa167436613f72b,e3024bcc4c26dafa78d4,3c94feec1065213db911,337384634a71832078c3,a906ba5cd9d7e8d2f8a1,2d95eaca808fa8bab822,[gitBranch=edas_micro]-[gitUser=zhaiwl]-[打包时间=2023-08-31 09:18]-[COMMIT_SHA=3f5f1af1259de0937647fcc19a13273d5c417529]
    mq:
      type: rocketmq
    rocketmq:
      producer:
        group-name: ARCHIVES_DEFAULT_GROUP
        namesrv-addr: namesrv.base.svc.cluster.local:9876
        max-message-size: 1024
        send-msg-timeout: 3000
        retry-times-when-send-failed: 2
    boot:
      blobstore:
        spring:
          boot:
            # 根据现场云存储类型进行更改：MinIOBlobStore（需部署MinIo）,
            # OSSBlobStore（阿里云）,OBSBlobStore(华为云)
            blob-store-impl-name: MinIOBlobStore
            primaryBId: 1
            routeStrategy: random
            store-nodes:
              - bId: 1
                # endPoint: http://minio.dev-guanghu.svc.cluster.local:9000
                endPoint: http://minio.base.svc.cluster.local:9000
                accessKey: admin
                secretKey: Dctm@1234
                bucketName: dataarchives
                desc: dataarchives
    archive:
      topic: TP_DATA_ARCHIVES
      group-name: ARCHIVES_DEFAULT_GROUP
    config:
      cache:
        init-caches:
          archives-other:
            name: other
            ttl: -1
webservice:
  enable: false
  oa:
    metadata_scheme_name:
    metadata_scheme_code:
    version_no:
    system_code:
    business_code:
    category_code:

dubbo:
  application:
    metadata-service-protocol: tri
  protocol:
    name: tri
    port: -1
  registry:
    address: zookeeper://zk-cs.base.svc.cluster.local:2181?client=curator
  consumer:
    check: false
  scan:
    base-packages: cn.amberdata.dataarchives.service.facade
buservice:
  zookeeper:
    host: zk-cs.base.svc.cluster.local:2181