spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            #是否允许cookie跨域  true允许
            allowCredentials: false
            #允许跨域的url * 则允许全部
            allowedOrigins: "*"
            #允许跨域的header * 则允许全部
            allowedHeaders: "*"
            # 允许跨域的方法 * 则全部
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      routes:
        - id: "micro"
          uri: "http://admin.app.svc.cluster.local:8888"
          predicates:
            - Path=/micro/**
          filters:
            - RewritePath=/micro/?(?<segment>.*),/adminapi/micro/$\{segment}
        - id: "admin-backend"
          uri: "http://admin.app.svc.cluster.local:8888"
          predicates:
            - Path=/adminapi/**
        - id: "metadata"
          uri: "http://metadata.app.svc.cluster.local:8888"
          predicates:
            - Path=/metadataapi/**
        - id: "flow"
          uri: "http://flow.app.svc.cluster.local:8888"
          predicates:
            - Path=/flowapi/**
        - id: "sgportal"
          uri: "http://sgportal.app.svc.cluster.local:8888"
          predicates:
            - Path=/sgportalapi/**
        - id: "dataarchives"
          uri: "http://dataarchives.app.svc.cluster.local:8888"
          predicates:
            - Path=/dataarchivesapi/**
        - id: "erms"
          uri: "http://erms.app.svc.cluster.local:8888"
          predicates:
            - Path=/ermsapi/**
        - id: "search"
          uri: "http://search.app.svc.cluster.local:8888"
          predicates:
            - Path=/searchapi/**
        - id: "format"
          uri: "http://format.app.svc.cluster.local:8888"
          predicates:
            - Path=/formatapi/**
        - id: "platform"
          uri: "http://platform.app.svc.cluster.local:8888"
          predicates:
            - Path=/platformapi/**
        - id: "mic"
          uri: "http://mic.app.svc.cluster.local:8888"
          predicates:
            - Path=/micapi/**
        - id: "transferreceiving"
          uri: "http://transferreceiving.app.svc.cluster.local:8888"
          predicates:
            - Path=/transferreceivingapi/**
        - id: "triple"
          uri: "http://triple.app.svc.cluster.local:8888"
          predicates:
            - Path=/tripleapi/**
        - id: "messagedispatch"
          uri: "http://messagedispatch.app.svc.cluster.local:8888"
          predicates:
            - Path=/messagedispatchapi/**
        - id: "km"
          uri: "http://km.app.svc.cluster.local:8888"
          predicates:
            - Path=/kmapi/**
        - id: "dm"
          uri: "http://km.app.svc.cluster.local:8888"
          predicates:
            - Path=/dmapi/**
        - id: "validator"
          uri: "http://validator.app.svc.cluster.local:8888"
          predicates:
            - Path=/validatorapi/**
dubbo:
  registry:
    address: zookeeper://zk-cs.base.svc.cluster.local:2181?client=curator
cn:
  amberdata:
    sso:
      login-domain: https://da.nbjb.gov.cn
buservice:
  zookeeper:
    host: zk-cs.base.svc.cluster.local:2181