spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://mysql.base.svc.cluster.local:3306/admin-backend?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: Dctm@1234
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  redis:
    database: 1
    host: redis.base.svc.cluster.local
    port: 6379
    password: Dctm@1234
  elasticsearch:
    rest:
      uris: http://elasticsearch.base.svc.cluster.local:9200
      username: admin
      password: admin
dubbo:
  registry:
    address: zookeeper://zk-zookeep.base.svc.cluster.local:2181?client=curator
cn:
  amberdata:
    boot:
      blobstore:
        spring:
          boot:
            blob-store-impl-name: MinIOBlobStore
            primaryBId: 1
            routeStrategy: random
            store-nodes: #修改点2
              - bId: 1
                access-key: admin
                bucket-name: plca
                end-point: http://minio.base.svc.cluster.local:9000
                secret-key: Dctm@1234
    rocketmq:
      producer:
        namesrv-addr: rocketmq.base.svc.cluster.local:9876
    sso:
      login-domain: http://10.68.190.225:84
      backend-uri-check: false
      white-header-enable: false
      white-header-host:
      white-redirect-enable: false
      white-redirect-host:
      default-redirect-url:
      security-xss-enable: false
    cdn:
      host: http://10.68.190.225:84/cdn/
    index:
      hash: c2f404cb,69c2d20d,577b0674,972b5732,aeb3e857,5f22d4aa,[gitBranch=feat_config]-[gitUser=cuimt]-[打包时间=2023-05-22 09:38]-[COMMIT_SHA=f13e9e9d824e3bbf1108ba06a0309fcc757d17eb]
    login:
      hash: 189b1f89a3f458a2a764,80ab492fe3d778817936,f0dde84cf7a460c8b133,7ff3fc35f9bdbaf81d86,d7df939f5822421f174e,be8f2d702cf494921370,[gitBranch=new_sso]-[gitUser=cuimt]-[打包时间=2023-04-21 18:19]-[COMMIT_SHA=948b7a876dee681f2475a66406b6d089537fef2f]
spi:
  org_user:
    enable: false
  jar:
    dir:
      org_user: /usr/spi
application:
  permission:
    enable: false
    tactics: FULL  #FULL OR VAGUE
logging:
  level:
    cn:
      amberdata:
        admin:
          root: debug
          authentication: debug
com:
  alipay:
    sofa:
      sofamq:
        config:
          topic: TP_ADMIN_NEW