//   ermsApiUrl : 'https://da.nbjb.gov.cn/ermsapi',
//   platformapi: 'https://da.nbjb.gov.cn/platformapi',
//   baseUrl : `https://da.nbjb.gov.cn/erms/#/`,
//   adminApiUrl : 'https://da.nbjb.gov.cn/adminapi',
//   cookieName : 'erms',
//   zlbUrl:'https://puser.zjzwfw.gov.cn/sso/mobile.do?action=oauth&scope=1&servicecode=dzdacy&goto=',
//   searchApiUrl:'https://da.nbjb.gov.cn/searchapi',
//   assetsUrl : '/zzdpc',
//   loginName: 'weizy_yh',
//   password: 'Y+zilsR88g9SZI8WOeHJlA==',
//   previewUrl : `https://da.nbjb.gov.cn/docview`,   // 预览的地址 域名